"""Add photo_url, enrollment_date, exit_date to products and expand status enum

Revision ID: 08449c298564
Revises: 1426230ad1d9
Create Date: 2026-06-16 12:23:54.241683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08449c298564'
down_revision: Union[str, None] = '1426230ad1d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('enrollment_date', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('exit_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'exit_date')
    op.drop_column('products', 'enrollment_date')
    op.drop_column('products', 'photo_url')
    # ### end Alembic commands ###
