"""Convert business_hours to JSON

Revision ID: 1426230ad1d9
Revises: 8ea1bd935198
Create Date: 2026-06-16 12:22:29.198707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1426230ad1d9'
down_revision: Union[str, None] = '8ea1bd935198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL to handle the type conversion properly
    op.execute("""
        ALTER TABLE locations 
        ALTER COLUMN business_hours TYPE JSON 
        USING NULL::json
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'business_hours',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
