"""Create student_profiles and staff_profiles tables (polymorphic refactor)

Revision ID: 198690b4ecc6
Revises: 08449c298564
Create Date: 2026-06-16 12:26:04.523089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '198690b4ecc6'
down_revision: Union[str, None] = '08449c298564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new tables first
    op.create_table('staff_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('salary_grade', sa.String(length=50), nullable=True),
    sa.Column('work_schedule', sa.String(length=255), nullable=True),
    sa.Column('supervisor_id', sa.Uuid(), nullable=True),
    sa.Column('employment_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('grade_class', sa.String(length=100), nullable=True),
    sa.Column('student_id', sa.String(length=100), nullable=True),
    sa.Column('guardians', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('academic_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    
    # Migrate existing student data
    connection = op.get_bind()
    connection.execute(sa.text("""
        INSERT INTO student_profiles (id, school_name, grade_class, guardians, enrollment_date)
        SELECT 
            id,
            school_name,
            grade_class,
            jsonb_build_object(
                'guardian1', jsonb_build_object(
                    'name', guardian1_name,
                    'relationship', guardian1_relationship,
                    'phone', guardian1_phone
                ),
                'guardian2', jsonb_build_object(
                    'name', guardian2_name,
                    'relationship', guardian2_relationship,
                    'phone', guardian2_phone
                )
            ),
            enrollment_date
        FROM products 
        WHERE product_type = 'student' 
        AND (school_name IS NOT NULL OR grade_class IS NOT NULL OR guardian1_name IS NOT NULL)
    """))
    
    # Drop old columns from products
    op.drop_column('products', 'guardian2_name')
    op.drop_column('products', 'guardian2_phone')
    op.drop_column('products', 'guardian2_relationship')
    op.drop_column('products', 'guardian1_name')
    op.drop_column('products', 'school_name')
    op.drop_column('products', 'guardian1_phone')
    op.drop_column('products', 'grade_class')
    op.drop_column('products', 'guardian1_relationship')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('guardian1_relationship', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('grade_class', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('guardian1_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('school_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('guardian1_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('guardian2_relationship', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('guardian2_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('guardian2_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('student_profiles')
    op.drop_table('staff_profiles')
    # ### end Alembic commands ###
