"""Create notifications, attendance_summaries, and payroll_records tables

Revision ID: 3f55c3123aa9
Revises: 198690b4ecc6
Create Date: 2026-06-16 12:28:11.983797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f55c3123aa9'
down_revision: Union[str, None] = '198690b4ecc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('first_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_work_minutes', sa.Integer(), nullable=False),
    sa.Column('total_overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('total_break_minutes', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('regular_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('holiday_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('attendance_notes', sa.String(length=500), nullable=True),
    sa.Column('calculation_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_summaries_location_id'), 'attendance_summaries', ['location_id'], unique=False)
    op.create_index(op.f('ix_attendance_summaries_product_id'), 'attendance_summaries', ['product_id'], unique=False)
    op.create_index(op.f('ix_attendance_summaries_summary_date'), 'attendance_summaries', ['summary_date'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_product_id'), 'notifications', ['product_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('payroll_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('payroll_period_start', sa.Date(), nullable=False),
    sa.Column('payroll_period_end', sa.Date(), nullable=False),
    sa.Column('total_regular_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_overtime_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_holiday_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_work_days', sa.Integer(), nullable=False),
    sa.Column('total_leave_days', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('overtime_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('holiday_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allowance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deduction', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('calculation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approval_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payroll_notes', sa.Text(), nullable=True),
    sa.Column('calculation_method', sa.String(length=50), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_records_payroll_period_end'), 'payroll_records', ['payroll_period_end'], unique=False)
    op.create_index(op.f('ix_payroll_records_payroll_period_start'), 'payroll_records', ['payroll_period_start'], unique=False)
    op.create_index(op.f('ix_payroll_records_product_id'), 'payroll_records', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_records_product_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_payroll_period_start'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_payroll_period_end'), table_name='payroll_records')
    op.drop_table('payroll_records')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_product_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_attendance_summaries_summary_date'), table_name='attendance_summaries')
    op.drop_index(op.f('ix_attendance_summaries_product_id'), table_name='attendance_summaries')
    op.drop_index(op.f('ix_attendance_summaries_location_id'), table_name='attendance_summaries')
    op.drop_table('attendance_summaries')
    # ### end Alembic commands ###
