"""Add voided_at to attendance_events

Revision ID: 4606c336c945
Revises: 3f55c3123aa9
Create Date: 2026-06-16 12:29:26.732339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4606c336c945'
down_revision: Union[str, None] = '3f55c3123aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_events', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_attendance_events_voided_at'), 'attendance_events', ['voided_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_events_voided_at'), table_name='attendance_events')
    op.drop_column('attendance_events', 'voided_at')
    # ### end Alembic commands ###
