"""Add created_at to attendance_events and add ondelete constraints

Revision ID: 489b8a7bac7d
Revises: 013
Create Date: 2026-06-16 12:10:27.786348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '489b8a7bac7d'
down_revision: Union[str, None] = '013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False))
    op.alter_column('attendance_events', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('fk_attendance_events_location_id_locations', 'attendance_events', type_='foreignkey')
    op.drop_constraint('attendance_events_recorded_by_user_id_fkey', 'attendance_events', type_='foreignkey')
    op.drop_constraint('attendance_events_product_id_fkey', 'attendance_events', type_='foreignkey')
    op.create_foreign_key(None, 'attendance_events', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'attendance_events', 'users', ['recorded_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'attendance_events', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('locations_code_key', 'locations', type_='unique')
    op.drop_index('ix_locations_code', table_name='locations')
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.drop_index('ix_product_scan_locations_location_id', table_name='product_scan_locations')
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_product_scan_locations_location_id', 'product_scan_locations', ['location_id'], unique=False)
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.create_index('ix_locations_code', 'locations', ['code'], unique=False)
    op.create_unique_constraint('locations_code_key', 'locations', ['code'])
    op.drop_constraint(None, 'attendance_events', type_='foreignkey')
    op.drop_constraint(None, 'attendance_events', type_='foreignkey')
    op.drop_constraint(None, 'attendance_events', type_='foreignkey')
    op.create_foreign_key('attendance_events_product_id_fkey', 'attendance_events', 'products', ['product_id'], ['id'])
    op.create_foreign_key('attendance_events_recorded_by_user_id_fkey', 'attendance_events', 'users', ['recorded_by_user_id'], ['id'])
    op.create_foreign_key('fk_attendance_events_location_id_locations', 'attendance_events', 'locations', ['location_id'], ['id'])
    op.alter_column('attendance_events', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('attendance_events', 'created_at')
    # ### end Alembic commands ###
