"""Add source field to attendance_events and remove manual_correction enum

Revision ID: 8117d89860d7
Revises: 489b8a7bac7d
Create Date: 2026-06-16 12:15:45.282534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8117d89860d7'
down_revision: Union[str, None] = '489b8a7bac7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_events', sa.Column('source', sa.String(length=30), server_default='scan', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_events', 'source')
    # ### end Alembic commands ###
