"""Add last_login_at to users and ip_address to refresh_tokens

Revision ID: 8ea1bd935198
Revises: 8117d89860d7
Create Date: 2026-06-16 12:20:12.193325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea1bd935198'
down_revision: Union[str, None] = '8117d89860d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('refresh_tokens', 'ip_address')
    # ### end Alembic commands ###
